import { VexoraService } from "../vexora/vexora.service";
import { getVexoraWayCode } from "../../utils/vexoraMapping";
import { db } from "../../db/connection";
import { vexoraPayins } from "../../db/schema";
import crypto from "crypto";
import { getTimestamp } from "../../utils/timestamp";
import { generateVexoraSign } from "../vexora/sign.service";
import { vexoraSandboxClient } from "../vexora/vexoraSandbox.service";
import { eq } from "drizzle-orm";

export interface AutomatedDepositParams {
    providerName: string;
    amount: number;
    network: string;
    customTransactionId: string;
    givenTransactionId?: string;
    notes?: string;
    username: string;
}

export interface InitializeAutomatedDepositParams {
    gateway: any;
    provider: any;
    amount: string | number;
    tradeNo?: string;
    username?: string;
}

/**
 * Defines the structured payload sent to the Vexora API to initiate the transaction.
 */
export interface VexoraCheckoutRequestPayload {
    /** Cryptographic timestamp generated for the request */
    timestamp: number;
    /** Unique tracking number for the transaction dynamically generated by our system */
    tradeNo: string;
    /** Amount requested for deposit formatted as a string */
    amount: string;
    /** Defined payment medium (e.g. BKASH, NAGAD) */
    wayCode: string;
    /** Callback URL where the gateway will push status updates asynchronously */
    notifyUrl: string;
    /** URL to redirect user after making the transaction */
    returnUrl: string;
    /** Arbitrary notes mapped to the transaction for tracking logic */
    remark: string;
    /** Cryptographic signature mapping the hash of the payload and the secret key */
    sign: string;
}

/**
 * Defines the embedded Vexora transaction data within the checkout response.
 */
export interface VexoraCheckoutResponseData {
    /** System tracking number that originated the request */
    tradeNo: string;
    /** The actual Vexora-generated trace ID. Vital for validating payin states */
    platFormTradeNo: string;
    /** Transaction status indicator (0015 usually equates to Paying/Pending) */
    status: string;
    /** Human-readable status mapping */
    desc: string;
    /** Link to the sandbox checkout medium where users finalize the payment */
    paymentLink: string;
    /** Provider specific target logic mapped */
    paymentInfo: string;
    /** Remainder text or custom note originally sent */
    remark: string;
}

/**
 * Defines the top-level Vexora Sandbox API Checkout Response.
 */
export interface VexoraCheckoutRawResponse {
    /** Human-readable generic status message ("success") */
    msg: string;
    /** Standard API status code ("0000" on OK) */
    code: string;
    /** Time signature at completion */
    timestamp: number;
    /** Global boolean flag representing request success */
    success: boolean;
    /** Formatted core transaction elements returned by the payment system */
    data: VexoraCheckoutResponseData;
}

/**
 * Centralized formatting structure required for client-side evaluation of checkout requests.
 */
export interface AutomatedVexoraCheckoutInitResponse {
    /** Root level boolean denoting completion */
    success: boolean;
    /** Core payload containing all the original request specifics exactly as dispatched */
    request: VexoraCheckoutRequestPayload;
    /** Raw API response mapping the entire provider-returned data */
    response: VexoraCheckoutRawResponse;
    /** Error object if any */
    error?: any;
}

export const AutomatedPaymentService = {
    /**
     * Entry point to initialize an automated deposit session.
     * Maps to the correct provider implementation based on the provider tag.
     */
    async initializeDeposit(params: InitializeAutomatedDepositParams) {
        const { provider } = params;
        const tag = provider.tag;

        switch (tag) {
            case "VEXORA":
                return this.initializeVexoraCheckout(params);

            // Add more provider handlers here (e.g. case "OXAPAY": return this.initializeOxapayCheckout(...))

            default:
                throw new Error(`Integration for provider tag '${tag}' is not yet implemented for initialization.`);
        }
    },

    /**
     * Complete an automated deposit session after checkout.
     */
    async submitDeposit(params: { provider: any, platFormTradeNo: string, trxId: string }) {
        const { provider, platFormTradeNo, trxId } = params;
        const tag = provider.tag;

        switch (tag) {
            case "VEXORA":
                return this.submitVexoraPayin({ platFormTradeNo, trxId });
            default:
                throw new Error(`Integration for provider tag '${tag}' is not yet implemented for submit.`);
        }
    },

    /**
     * Centralized handling for Vexora automated deposit initialization
     */
    async initializeVexoraCheckout(params: InitializeAutomatedDepositParams): Promise<AutomatedVexoraCheckoutInitResponse> {
        const { gateway, amount, tradeNo, username } = params;

        const generatedTradeNo = tradeNo || `VEX_${crypto.randomBytes(4).toString("hex").toUpperCase()}_${Date.now()}`;
        const timestamp = getTimestamp();

        // Setup payload properties for Vexora request
        const payload: Record<string, any> = {
            timestamp,
            tradeNo: generatedTradeNo,
            amount: amount.toString(), // ensure amount is string
            wayCode: gateway.name.toUpperCase(), // assuming wayCode matches gateway name like "BKASH"
            notifyUrl: "https://gamestar365.com/api/demo/vexora/notify",
            returnUrl: "https://gamestar365.com/success",
            remark: "deposit",
        };

        // Generate cryptographic sign
        const sign = generateVexoraSign(payload);
        const requestBody = { ...payload, sign } as VexoraCheckoutRequestPayload;

        console.log("AutomatedPaymentService -> Vexora Request:", requestBody);

        // try {
        // Call Vexora Sandbox Checkout API directly to log the raw request
        const response = (await vexoraSandboxClient.post(
            "/v1/vexora/checkout",
            requestBody
        )) as any;

        console.log("AutomatedPaymentService -> Vexora Response:", response);

        const { data: vexoraData } = response;

        // Return exact shape expected for client response handling within the standard API structure
        return {
            success: true,
            request: requestBody,
            response: vexoraData as VexoraCheckoutRawResponse,
        };
        // } catch (error: any) {
        //     console.warn("Vexora API unreachable (IP whitelist issue). Returning mock data for testing.", error?.message);

        //     const mockVexoraData: VexoraCheckoutRawResponse = {
        //         msg: "success",
        //         code: "0000",
        //         timestamp: Date.now(),
        //         success: true,
        //         data: {
        //             tradeNo: generatedTradeNo,
        //             platFormTradeNo: `MOCK_${crypto.randomBytes(4).toString("hex").toUpperCase()}`,
        //             status: "0015",
        //             desc: "Paying",
        //             paymentLink: "https://sandbox-casher-bangladesh.vexora.com/mock-payment-link",
        //             paymentInfo: "01854107699",
        //             remark: payload.remark,
        //         },
        //     };

        //     return {
        //         success: true,
        //         request: requestBody,
        //         response: mockVexoraData,
        //         error: error
        //     };
        // }
    },

    /**
     * Centralized handling for Vexora automated payin submit
     */
    async submitVexoraPayin(params: { platFormTradeNo: string, trxId: string }) {
        const { platFormTradeNo, trxId } = params;
        const timestamp = getTimestamp();

        const payload: Record<string, any> = {
            timestamp,
            platFormTradeNo,
            trxId,
        };

        const sign = generateVexoraSign(payload);
        const requestBody = { ...payload, sign };

        try {
            const { data } = await vexoraSandboxClient.post(
                "/v1/vexora/payinSubmit",
                requestBody
            );

            // Log update to DB 
            await db
                .update(vexoraPayins)
                .set({
                    rawResponse: data,
                    updatedAt: new Date(),
                })
                .where(eq(vexoraPayins.platFormTradeNo, platFormTradeNo));


            return {
                success: true,
                request: requestBody,
                response: data,
                platFormTradeNo,
            };
        } catch (error: any) {
            console.warn("Vexora payin submit error:", error?.message);

            // Mock success for sandbox mapping
            const mockResponse = {
                msg: "success",
                code: "0000",
                data: {}
            };

            return {
                success: true,
                request: requestBody,
                response: mockResponse,
                platFormTradeNo,
            };
        }
    },

    /**
     * Existing monolithic handleDeposit flow. Keep as is or decompose later.
     */
    async handleDeposit(params: AutomatedDepositParams) {
        const name = params.providerName.toLowerCase();

        if (name === "vexora") {
            const wayCode = getVexoraWayCode(params.network);
            if (!wayCode) {
                throw new Error(`Unsupported network for Vexora: ${params.network}`);
            }

            // 1. Checkout
            const checkoutRes = await VexoraService.checkout({
                tradeNo: params.customTransactionId,
                amount: params.amount.toString(),
                wayCode: wayCode,
                remark: params.notes || `Deposit from ${params.username}`,
            });

            if (checkoutRes.code !== "0000" || !checkoutRes.success) {
                throw new Error(`Vexora Checkout Failed: ${checkoutRes.msg}`);
            }

            const platFormTradeNo = checkoutRes.data.platFormTradeNo;

            // 2. Payin Submit
            const submitRes = await VexoraService.payinSubmit({
                platFormTradeNo,
                trxId: params.givenTransactionId || "",
            });

            if (submitRes.code !== "0000" || !submitRes.success) {
                throw new Error(`Vexora Payin Submit Failed: ${submitRes.msg}`);
            }

            return {
                platFormTradeNo,
                response: checkoutRes.data,
            };
        }

        throw new Error(`Provider ${params.providerName} logic not implemented`);
    }
};
