import "dotenv/config";
import { adminUsers, users } from "../schema";
import { db } from "../connection";
import { sql } from "drizzle-orm";

export const seedAdminUsers = async () => {
  try {
    await db
      .insert(adminUsers)
      .values([
        {
          username: "admin1",
          fullname: "Admin One",
          phone: "1000000001",
          email: "admin1@example.com",
          password: "adminpass1",
          country: "CountryA",
          city: "CityA",
          street: "StreetA",
          minTrx: "0",
          maxTrx: "1000",
          currency: 1,
          role: "superAdmin" as any,
          refCode: "REFADMIN1",
          status: "active",
          isLoggedIn: false,
          isVerified: true,
          lastIp: "127.0.0.1",
          lastLogin: new Date(),
          device_type: "Desktop",
          device_name: "AdminPC",
          os_version: "Windows 10",
          browser: "Chrome",
          browser_version: "114.0",
          ip_address: "127.0.0.1",
          device_token: "token-admin1",
          createdBy: 1,
        },
        {
          username: "superagent1",
          fullname: "Super Agent One",
          phone: "1000000002",
          email: "superagent1@example.com",
          password: "superagentpass1",
          country: "CountryB",
          city: "CityB",
          street: "StreetB",
          minTrx: "10",
          maxTrx: "2000",
          currency: 1,
          refCode: "REFSUPERAGENT1",
          role: "superAgent" as any,
          status: "active",
          isLoggedIn: false,
          isVerified: true,
          lastIp: "127.0.0.2",
          lastLogin: new Date(),
          device_type: "Mobile",
          device_name: "SuperAgentPhone",
          os_version: "Android 12",
          browser: "Firefox",
          browser_version: "102.0",
          ip_address: "127.0.0.2",
          device_token: "token-superagent1",
          createdBy: 1,
        },
        {
          username: "agent1",
          fullname: "Agent One",
          phone: "1000000003",
          refCode: "REFAGENT1",
          email: "agent1@example.com",
          password: "agentpass1",
          country: "CountryC",
          city: "CityC",
          street: "StreetC",
          minTrx: "20",
          maxTrx: "3000",
          currency: 1,
          role: "agent",
          status: "active",
          isLoggedIn: false,
          isVerified: true,
          lastIp: "127.0.0.3",
          lastLogin: new Date(),
          device_type: "Tablet",
          device_name: "AgentTablet",
          os_version: "iOS 15",
          browser: "Safari",
          browser_version: "15.0",
          ip_address: "127.0.0.3",
          device_token: "token-agent1",
          createdBy: 2,
        },
        {
          username: "superaffiliate1",
          fullname: "Super Affiliate One",
          phone: "1000000004",
          refCode: "REFSUPERAFFILIATE1",
          email: "superaffiliate1@example.com",
          password: "superaffiliatepass1",
          country: "CountryD",
          city: "CityD",
          street: "StreetD",
          minTrx: "30",
          maxTrx: "4000",
          currency: 1,
          role: "superAffiliate",
          status: "active",
          isLoggedIn: false,
          isVerified: true,
          lastIp: "127.0.0.4",
          lastLogin: new Date(),
          device_type: "Desktop",
          device_name: "SuperAffiliatePC",
          os_version: "Windows 11",
          browser: "Edge",
          browser_version: "113.0",
          ip_address: "127.0.0.4",
          device_token: "token-superaffiliate1",
          createdBy: 2,
        },
        {
          username: "affiliate1",
          fullname: "Affiliate One",
          phone: "1000000005",
          refCode: "REFAFFILIATE1",
          email: "affiliate1@example.com",
          password: "affiliatepass1",
          country: "CountryE",
          city: "CityE",
          street: "StreetE",
          minTrx: "40",
          maxTrx: "5000",
          currency: 1,
          role: "affiliate",
          status: "active",
          isLoggedIn: false,
          isVerified: true,
          lastIp: "127.0.0.5",
          lastLogin: new Date(),
          device_type: "Mobile",
          device_name: "AffiliatePhone",
          os_version: "Android 13",
          browser: "Opera",
          browser_version: "99.0",
          ip_address: "127.0.0.5",
          device_token: "token-affiliate1",
          createdBy: 3,
        },
      ])
      .onDuplicateKeyUpdate({
        set: {
          email: sql`values(${adminUsers.email})`,
          phone: sql`values(${adminUsers.phone})`,
        },
      });
    console.log("✅ AdminUser seed data inserted successfully!");
  } catch (error) {
    console.error("❌ Failed to insert AdminUser seed data:", error);
  }
};
